spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_?createDatabaseIfNotExist=true&serverTimezone=Asia/Manila
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
